[package]
name = "opilio-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.6", features = ["canvas", "tokio"] }
rand = "0.8"
log = "0.4"
env_logger = "0.10"
cubic_spline = "1.0"
opilio-tui = { path = "../opilio-tui"}
time = { version = "0.3", features = ["local-offset"] }


[[bin]]
name = "opilio-gui"
path = "src/main.rs"
